import Head from "next/head";
import Link from "next/link";

export function Header() {
  return (
    <>
      <Head>
        <title>create head</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/">index</Link>
      <Link href="/about">about</Link>
    </>
  );
}
